import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { CardShadow, Icon, PageHeader } from "@/components/recruiter/RecruiterShell";
import { useServerFn } from "@tanstack/react-start";
import { upsertJob, suggestJobDescription, runJDAssist } from "@/lib/jobs.functions";
import { Dialog, DialogContent } from "@/components/ui/dialog";

export const Route = createFileRoute("/_authenticated/recruiter/jobs/new")({
  component: NewJob,
});

function NewJob() {
  const navigate = useNavigate();
  const createJobFn = useServerFn(upsertJob);
  const suggest = useServerFn(suggestJobDescription);
  const runJDAssistFn = useServerFn(runJDAssist);

  const [form, setForm] = useState({
    title: "",
    department: "",
    location: "",
    employment_type: "Full-time",
    description: "",
    requirements: "",
    competencies: {} as any,
  });
  const [experienceLevel, setExperienceLevel] = useState("Mid-level (3-5 years)");
  const [assistOpen, setAssistOpen] = useState(false);
  const [assistData, setAssistData] = useState<any>(null);

  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const set = <K extends keyof typeof form>(k: K, v: any) => setForm((f) => ({ ...f, [k]: v }));

  const save = async (status: "draft" | "open") => {
    if (!form.title) return toast.error("Title is required");
    setSaving(true);
    try {
      await createJobFn({
        data: {
          title: form.title,
          department: form.department || null,
          location: form.location || null,
          employmentType: form.employment_type || null,
          description: form.description || null,
          requirements: form.requirements || null,
          status,
          competencies: form.competencies || null,
        },
      });
      toast.success(status === "draft" ? "Saved as draft" : "Published");
      navigate({ to: "/recruiter/jobs" });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to save job description");
    } finally {
      setSaving(false);
    }
  };

  const handleAIAssist = async () => {
    if (!form.title) return toast.error("Please enter a job title first");
    setGenerating(true);
    try {
      const res = await runJDAssistFn({
        data: {
          title: form.title,
          department: form.department || null,
          experienceLevel,
          location: form.location || null,
          employmentType: form.employment_type,
        },
      });
      setAssistData(res);
      setAssistOpen(true);
      toast.success("Job spec package generated by AI!");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to run AI Assist");
    } finally {
      setGenerating(false);
    }
  };

  const handleAcceptAssist = () => {
    if (!assistData) return;

    // Check if manually entered content exists and ask for confirmation
    const hasManualContent = form.description.trim() || form.requirements.trim();
    if (hasManualContent) {
      const confirmOverwrite = window.confirm(
        "You have manually entered description or requirements. Do you want to overwrite them with the AI suggested content?"
      );
      if (!confirmOverwrite) return;
    }

    setForm((f) => ({
      ...f,
      description: assistData.description,
      requirements: assistData.requirements,
      competencies: assistData,
    }));

    setAssistOpen(false);
    toast.success("AI suggested spec applied to builder fields successfully!");
  };

  return (
    <>
      <div className="mb-md">
        <Link
          to="/recruiter/jobs"
          className="text-primary text-body-md hover:underline inline-flex items-center gap-1"
        >
          <Icon name="arrow_back" />
          Back to JDs
        </Link>
      </div>
      <PageHeader
        title="New Job Description"
        subtitle="Define the role; your AI persona will calibrate to these requirements."
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-lg">
        <CardShadow className="lg:col-span-2 p-lg space-y-md">
          <Field label="Title">
            <input
              value={form.title}
              onChange={(e) => set("title", e.target.value)}
              className="input"
              placeholder="Senior Software Engineer"
            />
          </Field>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-md">
            <Field label="Department">
              <input
                value={form.department}
                onChange={(e) => set("department", e.target.value)}
                className="input"
                placeholder="Engineering"
              />
            </Field>
            <Field label="Location">
              <input
                value={form.location}
                onChange={(e) => set("location", e.target.value)}
                className="input"
                placeholder="Remote / NYC"
              />
            </Field>
            <Field label="Employment Type">
              <select
                value={form.employment_type}
                onChange={(e) => set("employment_type", e.target.value)}
                className="input"
              >
                <option>Full-time</option>
                <option>Part-time</option>
                <option>Contract</option>
                <option>Intern</option>
              </select>
            </Field>
          </div>
          <Field label="Description">
            <textarea
              rows={6}
              value={form.description}
              onChange={(e) => set("description", e.target.value)}
              className="input"
              placeholder="What the candidate will own…"
            />
          </Field>
          <Field label="Requirements">
            <textarea
              rows={6}
              value={form.requirements}
              onChange={(e) => set("requirements", e.target.value)}
              className="input"
              placeholder="Must-have skills, experience, qualifications…"
            />
          </Field>
          <div className="flex gap-sm pt-md">
            <button
              type="button"
              disabled={saving}
              onClick={() => save("draft")}
              className="px-4 py-2 border border-outline-variant rounded-lg hover:bg-surface-container-low disabled:opacity-50"
            >
              Save Draft
            </button>
            <button
              type="button"
              disabled={saving}
              onClick={() => save("open")}
              className="px-4 py-2 bg-primary text-on-primary rounded-lg hover:brightness-110 disabled:opacity-50"
            >
              Publish
            </button>
          </div>
        </CardShadow>

        <CardShadow className="p-lg ai-insight space-y-md h-fit">
          <h3 className="text-headline-sm flex items-center gap-2">
            <Icon name="auto_awesome" className="text-secondary" />
            AI Assist
          </h3>
          <p className="text-body-md text-on-surface-variant">
            Generate detailed job description, responsibilities, competencies, and evaluation rubrics automatically.
          </p>

          <Field label="Experience Level">
            <select
              value={experienceLevel}
              onChange={(e) => setExperienceLevel(e.target.value)}
              className="input bg-surface"
            >
              <option>Junior (0-2 years)</option>
              <option>Mid-level (3-5 years)</option>
              <option>Senior (5-8 years)</option>
              <option>Lead (8+ years)</option>
              <option>Executive (10+ years)</option>
            </select>
          </Field>

          <button
            type="button"
            disabled={generating}
            onClick={handleAIAssist}
            className="w-full px-3 py-2.5 bg-primary text-on-primary rounded-lg flex items-center justify-center gap-2 hover:brightness-110 disabled:opacity-50 cursor-pointer font-semibold text-sm"
          >
            <Icon name="auto_fix_high" />
            {generating ? "Generating..." : "Run AI Assist"}
          </button>
        </CardShadow>
      </div>

      <Dialog open={assistOpen} onOpenChange={setAssistOpen}>
        <DialogContent className="max-w-[1000px] w-[95vw] max-h-[85vh] p-0 flex flex-col overflow-hidden bg-white border border-outline-variant shadow-2xl rounded-2xl">
          <header className="px-6 py-4 border-b border-outline-variant bg-surface-container-low flex justify-between items-center shrink-0">
            <div className="flex items-center gap-2.5">
              <span className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
                <Icon name="auto_awesome" className="text-[20px]" />
              </span>
              <div>
                <h3 className="text-lg font-semibold text-on-surface">AI Generated Job Spec Details</h3>
                <p className="text-xs text-on-surface-variant font-medium">Review, customize, and accept into your JD Builder</p>
              </div>
            </div>
            <button 
              onClick={() => setAssistOpen(false)}
              className="p-1.5 hover:bg-surface-container-high rounded text-on-surface-variant flex items-center justify-center"
            >
              <Icon name="close" className="text-lg" />
            </button>
          </header>

          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {assistData && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Left Column: Descriptions */}
                <div className="space-y-4">
                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Professional Job Description</label>
                    <textarea
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      rows={6}
                      value={assistData.description || ""}
                      onChange={(e) => setAssistData({ ...assistData, description: e.target.value })}
                    />
                  </div>

                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Requirements (Markdowns supported)</label>
                    <textarea
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      rows={6}
                      value={assistData.requirements || ""}
                      onChange={(e) => setAssistData({ ...assistData, requirements: e.target.value })}
                    />
                  </div>

                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Experience Requirements</label>
                    <textarea
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      rows={3}
                      value={assistData.experienceRequirements || ""}
                      onChange={(e) => setAssistData({ ...assistData, experienceRequirements: e.target.value })}
                    />
                  </div>
                </div>

                {/* Right Column: Key Details & Lists */}
                <div className="space-y-4">
                  {/* Key Responsibilities */}
                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Key Responsibilities (Comma separated)</label>
                    <textarea
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      rows={3}
                      value={Array.isArray(assistData.keyResponsibilities) ? assistData.keyResponsibilities.join(", ") : assistData.keyResponsibilities || ""}
                      onChange={(e) => setAssistData({
                        ...assistData,
                        keyResponsibilities: e.target.value.split(",").map((s: string) => s.trim()).filter(Boolean)
                      })}
                    />
                  </div>

                  {/* Required & Preferred Skills */}
                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Required Skills (Comma separated)</label>
                    <input
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      value={Array.isArray(assistData.requiredSkills) ? assistData.requiredSkills.join(", ") : assistData.requiredSkills || ""}
                      onChange={(e) => setAssistData({
                        ...assistData,
                        requiredSkills: e.target.value.split(",").map((s: string) => s.trim()).filter(Boolean)
                      })}
                    />
                  </div>

                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Preferred Skills (Comma separated)</label>
                    <input
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      value={Array.isArray(assistData.preferredSkills) ? assistData.preferredSkills.join(", ") : assistData.preferredSkills || ""}
                      onChange={(e) => setAssistData({
                        ...assistData,
                        preferredSkills: e.target.value.split(",").map((s: string) => s.trim()).filter(Boolean)
                      })}
                    />
                  </div>

                  {/* Technical & Soft Skills */}
                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Technical Skills (Comma separated)</label>
                    <input
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      value={Array.isArray(assistData.technicalSkills) ? assistData.technicalSkills.join(", ") : assistData.technicalSkills || ""}
                      onChange={(e) => setAssistData({
                        ...assistData,
                        technicalSkills: e.target.value.split(",").map((s: string) => s.trim()).filter(Boolean)
                      })}
                    />
                  </div>

                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Soft Skills (Comma separated)</label>
                    <input
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      value={Array.isArray(assistData.softSkills) ? assistData.softSkills.join(", ") : assistData.softSkills || ""}
                      onChange={(e) => setAssistData({
                        ...assistData,
                        softSkills: e.target.value.split(",").map((s: string) => s.trim()).filter(Boolean)
                      })}
                    />
                  </div>

                  {/* Minimum Qualifications */}
                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Minimum Qualifications (Comma separated)</label>
                    <textarea
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      rows={2}
                      value={Array.isArray(assistData.minimumQualifications) ? assistData.minimumQualifications.join(", ") : assistData.minimumQualifications || ""}
                      onChange={(e) => setAssistData({
                        ...assistData,
                        minimumQualifications: e.target.value.split(",").map((s: string) => s.trim()).filter(Boolean)
                      })}
                    />
                  </div>

                  {/* Interview Focus Areas */}
                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Interview Focus Areas (Comma separated)</label>
                    <textarea
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      rows={2}
                      value={Array.isArray(assistData.interviewFocusAreas) ? assistData.interviewFocusAreas.join(", ") : assistData.interviewFocusAreas || ""}
                      onChange={(e) => setAssistData({
                        ...assistData,
                        interviewFocusAreas: e.target.value.split(",").map((s: string) => s.trim()).filter(Boolean)
                      })}
                    />
                  </div>

                  {/* Evaluation Criteria */}
                  <div className="p-4 border border-outline-variant rounded-xl space-y-2 bg-surface-container-lowest">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider block">Evaluation Criteria (Comma separated)</label>
                    <textarea
                      className="w-full p-2 border border-outline-variant rounded-md text-sm bg-surface outline-none"
                      rows={2}
                      value={Array.isArray(assistData.evaluationCriteria) ? assistData.evaluationCriteria.join(", ") : assistData.evaluationCriteria || ""}
                      onChange={(e) => setAssistData({
                        ...assistData,
                        evaluationCriteria: e.target.value.split(",").map((s: string) => s.trim()).filter(Boolean)
                      })}
                    />
                  </div>
                </div>
              </div>
            )}
          </div>

          <footer className="px-6 py-3 border-t border-outline-variant bg-surface-container-low flex justify-between items-center shrink-0">
            <button
              onClick={() => setAssistOpen(false)}
              className="px-4 py-2 border border-outline-variant rounded-lg text-sm text-on-surface hover:bg-surface-container-high font-medium"
            >
              Discard
            </button>
            <div className="flex gap-2">
              <button
                onClick={handleAIAssist}
                className="px-4 py-2 border border-primary text-primary rounded-lg text-sm hover:bg-primary/5 font-semibold flex items-center gap-1.5"
              >
                <Icon name="refresh" className="text-sm" /> Regenerate
              </button>
              <button
                onClick={handleAcceptAssist}
                className="px-5 py-2 bg-primary text-on-primary rounded-lg text-sm hover:brightness-110 font-semibold"
              >
                Accept & Apply
              </button>
            </div>
          </footer>
        </DialogContent>
      </Dialog>

      <style>{`.input { width:100%; padding:0.5rem 0.75rem; background: var(--surface); border:1px solid var(--outline-variant); border-radius:0.5rem; outline:none; }
        .input:focus { box-shadow: 0 0 0 2px var(--primary-container); }`}</style>
    </>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="text-label-caps uppercase text-on-surface-variant block mb-1">{label}</span>
      {children}
    </label>
  );
}
