/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthenticatedRecruiterRouteRouteImport } from './routes/_authenticated/recruiter/route'
import { Route as AuthenticatedCandidateRouteRouteImport } from './routes/_authenticated/candidate/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedRecruiterIndexRouteImport } from './routes/_authenticated/recruiter/index'
import { Route as AuthenticatedCandidateIndexRouteImport } from './routes/_authenticated/candidate/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedCandidateSystemCheckRouteImport } from './routes/_authenticated/candidate/system-check'
import { Route as AuthenticatedCandidatePrepareRouteImport } from './routes/_authenticated/candidate/prepare'
import { Route as AuthenticatedCandidateInterviewRouteImport } from './routes/_authenticated/candidate/interview'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin/security'
import { Route as AuthenticatedRecruiterSchedulingIndexRouteImport } from './routes/_authenticated/recruiter/scheduling/index'
import { Route as AuthenticatedRecruiterReportsIndexRouteImport } from './routes/_authenticated/recruiter/reports/index'
import { Route as AuthenticatedRecruiterQuestionsIndexRouteImport } from './routes/_authenticated/recruiter/questions/index'
import { Route as AuthenticatedRecruiterPersonasIndexRouteImport } from './routes/_authenticated/recruiter/personas/index'
import { Route as AuthenticatedRecruiterMonitorIndexRouteImport } from './routes/_authenticated/recruiter/monitor/index'
import { Route as AuthenticatedRecruiterJobsIndexRouteImport } from './routes/_authenticated/recruiter/jobs/index'
import { Route as AuthenticatedRecruiterCandidatesIndexRouteImport } from './routes/_authenticated/recruiter/candidates/index'
import { Route as AuthenticatedRecruiterAnalyticsIndexRouteImport } from './routes/_authenticated/recruiter/analytics/index'
import { Route as AuthenticatedAdminOrganizationsIndexRouteImport } from './routes/_authenticated/admin/organizations/index'
import { Route as ApiPublicCronInterviewRemindersRouteImport } from './routes/api/public/cron/interview-reminders'
import { Route as AuthenticatedRecruiterReportsComprehensiveRouteImport } from './routes/_authenticated/recruiter/reports/comprehensive'
import { Route as AuthenticatedRecruiterReportsInterviewIdRouteImport } from './routes/_authenticated/recruiter/reports/$interviewId'
import { Route as AuthenticatedRecruiterPersonasPromptRouteImport } from './routes/_authenticated/recruiter/personas/prompt'
import { Route as AuthenticatedRecruiterPersonasNewRouteImport } from './routes/_authenticated/recruiter/personas/new'
import { Route as AuthenticatedRecruiterJobsNewRouteImport } from './routes/_authenticated/recruiter/jobs/new'
import { Route as AuthenticatedRecruiterCandidatesIdRouteImport } from './routes/_authenticated/recruiter/candidates/$id'
import { Route as AuthenticatedAdminOrganizationsIntelligenceRouteImport } from './routes/_authenticated/admin/organizations/intelligence'
import { Route as AuthenticatedAdminOrganizationsIdRouteImport } from './routes/_authenticated/admin/organizations/$id'
import { Route as AuthenticatedRecruiterCandidatesIdResumeRouteImport } from './routes/_authenticated/recruiter/candidates/$id.resume'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecruiterRouteRoute =
  AuthenticatedRecruiterRouteRouteImport.update({
    id: '/recruiter',
    path: '/recruiter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateRouteRoute =
  AuthenticatedCandidateRouteRouteImport.update({
    id: '/candidate',
    path: '/candidate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruiterIndexRoute =
  AuthenticatedRecruiterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedCandidateIndexRoute =
  AuthenticatedCandidateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidateSystemCheckRoute =
  AuthenticatedCandidateSystemCheckRouteImport.update({
    id: '/system-check',
    path: '/system-check',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidatePrepareRoute =
  AuthenticatedCandidatePrepareRouteImport.update({
    id: '/prepare',
    path: '/prepare',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateInterviewRoute =
  AuthenticatedCandidateInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedRecruiterSchedulingIndexRoute =
  AuthenticatedRecruiterSchedulingIndexRouteImport.update({
    id: '/scheduling/',
    path: '/scheduling/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterReportsIndexRoute =
  AuthenticatedRecruiterReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterQuestionsIndexRoute =
  AuthenticatedRecruiterQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterPersonasIndexRoute =
  AuthenticatedRecruiterPersonasIndexRouteImport.update({
    id: '/personas/',
    path: '/personas/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterMonitorIndexRoute =
  AuthenticatedRecruiterMonitorIndexRouteImport.update({
    id: '/monitor/',
    path: '/monitor/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsIndexRoute =
  AuthenticatedRecruiterJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterCandidatesIndexRoute =
  AuthenticatedRecruiterCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterAnalyticsIndexRoute =
  AuthenticatedRecruiterAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationsIndexRoute =
  AuthenticatedAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicCronInterviewRemindersRoute =
  ApiPublicCronInterviewRemindersRouteImport.update({
    id: '/api/public/cron/interview-reminders',
    path: '/api/public/cron/interview-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRecruiterReportsComprehensiveRoute =
  AuthenticatedRecruiterReportsComprehensiveRouteImport.update({
    id: '/reports/comprehensive',
    path: '/reports/comprehensive',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterReportsInterviewIdRoute =
  AuthenticatedRecruiterReportsInterviewIdRouteImport.update({
    id: '/reports/$interviewId',
    path: '/reports/$interviewId',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterPersonasPromptRoute =
  AuthenticatedRecruiterPersonasPromptRouteImport.update({
    id: '/personas/prompt',
    path: '/personas/prompt',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterPersonasNewRoute =
  AuthenticatedRecruiterPersonasNewRouteImport.update({
    id: '/personas/new',
    path: '/personas/new',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsNewRoute =
  AuthenticatedRecruiterJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterCandidatesIdRoute =
  AuthenticatedRecruiterCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationsIntelligenceRoute =
  AuthenticatedAdminOrganizationsIntelligenceRouteImport.update({
    id: '/organizations/intelligence',
    path: '/organizations/intelligence',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationsIdRoute =
  AuthenticatedAdminOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedRecruiterCandidatesIdResumeRoute =
  AuthenticatedRecruiterCandidatesIdResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => AuthenticatedRecruiterCandidatesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/candidate': typeof AuthenticatedCandidateRouteRouteWithChildren
  '/recruiter': typeof AuthenticatedRecruiterRouteRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/candidate/interview': typeof AuthenticatedCandidateInterviewRoute
  '/candidate/prepare': typeof AuthenticatedCandidatePrepareRoute
  '/candidate/system-check': typeof AuthenticatedCandidateSystemCheckRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/admin/organizations/intelligence': typeof AuthenticatedAdminOrganizationsIntelligenceRoute
  '/recruiter/candidates/$id': typeof AuthenticatedRecruiterCandidatesIdRouteWithChildren
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/recruiter/personas/new': typeof AuthenticatedRecruiterPersonasNewRoute
  '/recruiter/personas/prompt': typeof AuthenticatedRecruiterPersonasPromptRoute
  '/recruiter/reports/$interviewId': typeof AuthenticatedRecruiterReportsInterviewIdRoute
  '/recruiter/reports/comprehensive': typeof AuthenticatedRecruiterReportsComprehensiveRoute
  '/api/public/cron/interview-reminders': typeof ApiPublicCronInterviewRemindersRoute
  '/admin/organizations/': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/recruiter/analytics/': typeof AuthenticatedRecruiterAnalyticsIndexRoute
  '/recruiter/candidates/': typeof AuthenticatedRecruiterCandidatesIndexRoute
  '/recruiter/jobs/': typeof AuthenticatedRecruiterJobsIndexRoute
  '/recruiter/monitor/': typeof AuthenticatedRecruiterMonitorIndexRoute
  '/recruiter/personas/': typeof AuthenticatedRecruiterPersonasIndexRoute
  '/recruiter/questions/': typeof AuthenticatedRecruiterQuestionsIndexRoute
  '/recruiter/reports/': typeof AuthenticatedRecruiterReportsIndexRoute
  '/recruiter/scheduling/': typeof AuthenticatedRecruiterSchedulingIndexRoute
  '/recruiter/candidates/$id/resume': typeof AuthenticatedRecruiterCandidatesIdResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/join/$token': typeof JoinTokenRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/candidate/interview': typeof AuthenticatedCandidateInterviewRoute
  '/candidate/prepare': typeof AuthenticatedCandidatePrepareRoute
  '/candidate/system-check': typeof AuthenticatedCandidateSystemCheckRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/candidate': typeof AuthenticatedCandidateIndexRoute
  '/recruiter': typeof AuthenticatedRecruiterIndexRoute
  '/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/admin/organizations/intelligence': typeof AuthenticatedAdminOrganizationsIntelligenceRoute
  '/recruiter/candidates/$id': typeof AuthenticatedRecruiterCandidatesIdRouteWithChildren
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/recruiter/personas/new': typeof AuthenticatedRecruiterPersonasNewRoute
  '/recruiter/personas/prompt': typeof AuthenticatedRecruiterPersonasPromptRoute
  '/recruiter/reports/$interviewId': typeof AuthenticatedRecruiterReportsInterviewIdRoute
  '/recruiter/reports/comprehensive': typeof AuthenticatedRecruiterReportsComprehensiveRoute
  '/api/public/cron/interview-reminders': typeof ApiPublicCronInterviewRemindersRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/recruiter/analytics': typeof AuthenticatedRecruiterAnalyticsIndexRoute
  '/recruiter/candidates': typeof AuthenticatedRecruiterCandidatesIndexRoute
  '/recruiter/jobs': typeof AuthenticatedRecruiterJobsIndexRoute
  '/recruiter/monitor': typeof AuthenticatedRecruiterMonitorIndexRoute
  '/recruiter/personas': typeof AuthenticatedRecruiterPersonasIndexRoute
  '/recruiter/questions': typeof AuthenticatedRecruiterQuestionsIndexRoute
  '/recruiter/reports': typeof AuthenticatedRecruiterReportsIndexRoute
  '/recruiter/scheduling': typeof AuthenticatedRecruiterSchedulingIndexRoute
  '/recruiter/candidates/$id/resume': typeof AuthenticatedRecruiterCandidatesIdResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/candidate': typeof AuthenticatedCandidateRouteRouteWithChildren
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRouteRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/candidate/interview': typeof AuthenticatedCandidateInterviewRoute
  '/_authenticated/candidate/prepare': typeof AuthenticatedCandidatePrepareRoute
  '/_authenticated/candidate/system-check': typeof AuthenticatedCandidateSystemCheckRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/_authenticated/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/_authenticated/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/_authenticated/admin/organizations/intelligence': typeof AuthenticatedAdminOrganizationsIntelligenceRoute
  '/_authenticated/recruiter/candidates/$id': typeof AuthenticatedRecruiterCandidatesIdRouteWithChildren
  '/_authenticated/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/_authenticated/recruiter/personas/new': typeof AuthenticatedRecruiterPersonasNewRoute
  '/_authenticated/recruiter/personas/prompt': typeof AuthenticatedRecruiterPersonasPromptRoute
  '/_authenticated/recruiter/reports/$interviewId': typeof AuthenticatedRecruiterReportsInterviewIdRoute
  '/_authenticated/recruiter/reports/comprehensive': typeof AuthenticatedRecruiterReportsComprehensiveRoute
  '/api/public/cron/interview-reminders': typeof ApiPublicCronInterviewRemindersRoute
  '/_authenticated/admin/organizations/': typeof AuthenticatedAdminOrganizationsIndexRoute
  '/_authenticated/recruiter/analytics/': typeof AuthenticatedRecruiterAnalyticsIndexRoute
  '/_authenticated/recruiter/candidates/': typeof AuthenticatedRecruiterCandidatesIndexRoute
  '/_authenticated/recruiter/jobs/': typeof AuthenticatedRecruiterJobsIndexRoute
  '/_authenticated/recruiter/monitor/': typeof AuthenticatedRecruiterMonitorIndexRoute
  '/_authenticated/recruiter/personas/': typeof AuthenticatedRecruiterPersonasIndexRoute
  '/_authenticated/recruiter/questions/': typeof AuthenticatedRecruiterQuestionsIndexRoute
  '/_authenticated/recruiter/reports/': typeof AuthenticatedRecruiterReportsIndexRoute
  '/_authenticated/recruiter/scheduling/': typeof AuthenticatedRecruiterSchedulingIndexRoute
  '/_authenticated/recruiter/candidates/$id/resume': typeof AuthenticatedRecruiterCandidatesIdResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/candidate'
    | '/recruiter'
    | '/join/$token'
    | '/admin/security'
    | '/admin/settings'
    | '/candidate/interview'
    | '/candidate/prepare'
    | '/candidate/system-check'
    | '/api/public/health'
    | '/admin/'
    | '/candidate/'
    | '/recruiter/'
    | '/admin/organizations/$id'
    | '/admin/organizations/intelligence'
    | '/recruiter/candidates/$id'
    | '/recruiter/jobs/new'
    | '/recruiter/personas/new'
    | '/recruiter/personas/prompt'
    | '/recruiter/reports/$interviewId'
    | '/recruiter/reports/comprehensive'
    | '/api/public/cron/interview-reminders'
    | '/admin/organizations/'
    | '/recruiter/analytics/'
    | '/recruiter/candidates/'
    | '/recruiter/jobs/'
    | '/recruiter/monitor/'
    | '/recruiter/personas/'
    | '/recruiter/questions/'
    | '/recruiter/reports/'
    | '/recruiter/scheduling/'
    | '/recruiter/candidates/$id/resume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/reset-password'
    | '/join/$token'
    | '/admin/security'
    | '/admin/settings'
    | '/candidate/interview'
    | '/candidate/prepare'
    | '/candidate/system-check'
    | '/api/public/health'
    | '/admin'
    | '/candidate'
    | '/recruiter'
    | '/admin/organizations/$id'
    | '/admin/organizations/intelligence'
    | '/recruiter/candidates/$id'
    | '/recruiter/jobs/new'
    | '/recruiter/personas/new'
    | '/recruiter/personas/prompt'
    | '/recruiter/reports/$interviewId'
    | '/recruiter/reports/comprehensive'
    | '/api/public/cron/interview-reminders'
    | '/admin/organizations'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/jobs'
    | '/recruiter/monitor'
    | '/recruiter/personas'
    | '/recruiter/questions'
    | '/recruiter/reports'
    | '/recruiter/scheduling'
    | '/recruiter/candidates/$id/resume'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-denied'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/candidate'
    | '/_authenticated/recruiter'
    | '/join/$token'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/settings'
    | '/_authenticated/candidate/interview'
    | '/_authenticated/candidate/prepare'
    | '/_authenticated/candidate/system-check'
    | '/api/public/health'
    | '/_authenticated/admin/'
    | '/_authenticated/candidate/'
    | '/_authenticated/recruiter/'
    | '/_authenticated/admin/organizations/$id'
    | '/_authenticated/admin/organizations/intelligence'
    | '/_authenticated/recruiter/candidates/$id'
    | '/_authenticated/recruiter/jobs/new'
    | '/_authenticated/recruiter/personas/new'
    | '/_authenticated/recruiter/personas/prompt'
    | '/_authenticated/recruiter/reports/$interviewId'
    | '/_authenticated/recruiter/reports/comprehensive'
    | '/api/public/cron/interview-reminders'
    | '/_authenticated/admin/organizations/'
    | '/_authenticated/recruiter/analytics/'
    | '/_authenticated/recruiter/candidates/'
    | '/_authenticated/recruiter/jobs/'
    | '/_authenticated/recruiter/monitor/'
    | '/_authenticated/recruiter/personas/'
    | '/_authenticated/recruiter/questions/'
    | '/_authenticated/recruiter/reports/'
    | '/_authenticated/recruiter/scheduling/'
    | '/_authenticated/recruiter/candidates/$id/resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicCronInterviewRemindersRoute: typeof ApiPublicCronInterviewRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate': {
      id: '/_authenticated/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof AuthenticatedCandidateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter/': {
      id: '/_authenticated/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof AuthenticatedRecruiterIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/candidate/': {
      id: '/_authenticated/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AuthenticatedCandidateIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidate/system-check': {
      id: '/_authenticated/candidate/system-check'
      path: '/system-check'
      fullPath: '/candidate/system-check'
      preLoaderRoute: typeof AuthenticatedCandidateSystemCheckRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/prepare': {
      id: '/_authenticated/candidate/prepare'
      path: '/prepare'
      fullPath: '/candidate/prepare'
      preLoaderRoute: typeof AuthenticatedCandidatePrepareRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/interview': {
      id: '/_authenticated/candidate/interview'
      path: '/interview'
      fullPath: '/candidate/interview'
      preLoaderRoute: typeof AuthenticatedCandidateInterviewRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/recruiter/scheduling/': {
      id: '/_authenticated/recruiter/scheduling/'
      path: '/scheduling'
      fullPath: '/recruiter/scheduling/'
      preLoaderRoute: typeof AuthenticatedRecruiterSchedulingIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/reports/': {
      id: '/_authenticated/recruiter/reports/'
      path: '/reports'
      fullPath: '/recruiter/reports/'
      preLoaderRoute: typeof AuthenticatedRecruiterReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/questions/': {
      id: '/_authenticated/recruiter/questions/'
      path: '/questions'
      fullPath: '/recruiter/questions/'
      preLoaderRoute: typeof AuthenticatedRecruiterQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/personas/': {
      id: '/_authenticated/recruiter/personas/'
      path: '/personas'
      fullPath: '/recruiter/personas/'
      preLoaderRoute: typeof AuthenticatedRecruiterPersonasIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/monitor/': {
      id: '/_authenticated/recruiter/monitor/'
      path: '/monitor'
      fullPath: '/recruiter/monitor/'
      preLoaderRoute: typeof AuthenticatedRecruiterMonitorIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/jobs/': {
      id: '/_authenticated/recruiter/jobs/'
      path: '/jobs'
      fullPath: '/recruiter/jobs/'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/candidates/': {
      id: '/_authenticated/recruiter/candidates/'
      path: '/candidates'
      fullPath: '/recruiter/candidates/'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/analytics/': {
      id: '/_authenticated/recruiter/analytics/'
      path: '/analytics'
      fullPath: '/recruiter/analytics/'
      preLoaderRoute: typeof AuthenticatedRecruiterAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/admin/organizations/': {
      id: '/_authenticated/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/cron/interview-reminders': {
      id: '/api/public/cron/interview-reminders'
      path: '/api/public/cron/interview-reminders'
      fullPath: '/api/public/cron/interview-reminders'
      preLoaderRoute: typeof ApiPublicCronInterviewRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter/reports/comprehensive': {
      id: '/_authenticated/recruiter/reports/comprehensive'
      path: '/reports/comprehensive'
      fullPath: '/recruiter/reports/comprehensive'
      preLoaderRoute: typeof AuthenticatedRecruiterReportsComprehensiveRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/reports/$interviewId': {
      id: '/_authenticated/recruiter/reports/$interviewId'
      path: '/reports/$interviewId'
      fullPath: '/recruiter/reports/$interviewId'
      preLoaderRoute: typeof AuthenticatedRecruiterReportsInterviewIdRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/personas/prompt': {
      id: '/_authenticated/recruiter/personas/prompt'
      path: '/personas/prompt'
      fullPath: '/recruiter/personas/prompt'
      preLoaderRoute: typeof AuthenticatedRecruiterPersonasPromptRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/personas/new': {
      id: '/_authenticated/recruiter/personas/new'
      path: '/personas/new'
      fullPath: '/recruiter/personas/new'
      preLoaderRoute: typeof AuthenticatedRecruiterPersonasNewRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/jobs/new': {
      id: '/_authenticated/recruiter/jobs/new'
      path: '/jobs/new'
      fullPath: '/recruiter/jobs/new'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsNewRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/candidates/$id': {
      id: '/_authenticated/recruiter/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/recruiter/candidates/$id'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/admin/organizations/intelligence': {
      id: '/_authenticated/admin/organizations/intelligence'
      path: '/organizations/intelligence'
      fullPath: '/admin/organizations/intelligence'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIntelligenceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/organizations/$id': {
      id: '/_authenticated/admin/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/recruiter/candidates/$id/resume': {
      id: '/_authenticated/recruiter/candidates/$id/resume'
      path: '/resume'
      fullPath: '/recruiter/candidates/$id/resume'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidatesIdResumeRouteImport
      parentRoute: typeof AuthenticatedRecruiterCandidatesIdRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrganizationsIdRoute: typeof AuthenticatedAdminOrganizationsIdRoute
  AuthenticatedAdminOrganizationsIntelligenceRoute: typeof AuthenticatedAdminOrganizationsIntelligenceRoute
  AuthenticatedAdminOrganizationsIndexRoute: typeof AuthenticatedAdminOrganizationsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminOrganizationsIdRoute:
      AuthenticatedAdminOrganizationsIdRoute,
    AuthenticatedAdminOrganizationsIntelligenceRoute:
      AuthenticatedAdminOrganizationsIntelligenceRoute,
    AuthenticatedAdminOrganizationsIndexRoute:
      AuthenticatedAdminOrganizationsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCandidateRouteRouteChildren {
  AuthenticatedCandidateInterviewRoute: typeof AuthenticatedCandidateInterviewRoute
  AuthenticatedCandidatePrepareRoute: typeof AuthenticatedCandidatePrepareRoute
  AuthenticatedCandidateSystemCheckRoute: typeof AuthenticatedCandidateSystemCheckRoute
  AuthenticatedCandidateIndexRoute: typeof AuthenticatedCandidateIndexRoute
}

const AuthenticatedCandidateRouteRouteChildren: AuthenticatedCandidateRouteRouteChildren =
  {
    AuthenticatedCandidateInterviewRoute: AuthenticatedCandidateInterviewRoute,
    AuthenticatedCandidatePrepareRoute: AuthenticatedCandidatePrepareRoute,
    AuthenticatedCandidateSystemCheckRoute:
      AuthenticatedCandidateSystemCheckRoute,
    AuthenticatedCandidateIndexRoute: AuthenticatedCandidateIndexRoute,
  }

const AuthenticatedCandidateRouteRouteWithChildren =
  AuthenticatedCandidateRouteRoute._addFileChildren(
    AuthenticatedCandidateRouteRouteChildren,
  )

interface AuthenticatedRecruiterCandidatesIdRouteChildren {
  AuthenticatedRecruiterCandidatesIdResumeRoute: typeof AuthenticatedRecruiterCandidatesIdResumeRoute
}

const AuthenticatedRecruiterCandidatesIdRouteChildren: AuthenticatedRecruiterCandidatesIdRouteChildren =
  {
    AuthenticatedRecruiterCandidatesIdResumeRoute:
      AuthenticatedRecruiterCandidatesIdResumeRoute,
  }

const AuthenticatedRecruiterCandidatesIdRouteWithChildren =
  AuthenticatedRecruiterCandidatesIdRoute._addFileChildren(
    AuthenticatedRecruiterCandidatesIdRouteChildren,
  )

interface AuthenticatedRecruiterRouteRouteChildren {
  AuthenticatedRecruiterIndexRoute: typeof AuthenticatedRecruiterIndexRoute
  AuthenticatedRecruiterCandidatesIdRoute: typeof AuthenticatedRecruiterCandidatesIdRouteWithChildren
  AuthenticatedRecruiterJobsNewRoute: typeof AuthenticatedRecruiterJobsNewRoute
  AuthenticatedRecruiterPersonasNewRoute: typeof AuthenticatedRecruiterPersonasNewRoute
  AuthenticatedRecruiterPersonasPromptRoute: typeof AuthenticatedRecruiterPersonasPromptRoute
  AuthenticatedRecruiterReportsInterviewIdRoute: typeof AuthenticatedRecruiterReportsInterviewIdRoute
  AuthenticatedRecruiterReportsComprehensiveRoute: typeof AuthenticatedRecruiterReportsComprehensiveRoute
  AuthenticatedRecruiterAnalyticsIndexRoute: typeof AuthenticatedRecruiterAnalyticsIndexRoute
  AuthenticatedRecruiterCandidatesIndexRoute: typeof AuthenticatedRecruiterCandidatesIndexRoute
  AuthenticatedRecruiterJobsIndexRoute: typeof AuthenticatedRecruiterJobsIndexRoute
  AuthenticatedRecruiterMonitorIndexRoute: typeof AuthenticatedRecruiterMonitorIndexRoute
  AuthenticatedRecruiterPersonasIndexRoute: typeof AuthenticatedRecruiterPersonasIndexRoute
  AuthenticatedRecruiterQuestionsIndexRoute: typeof AuthenticatedRecruiterQuestionsIndexRoute
  AuthenticatedRecruiterReportsIndexRoute: typeof AuthenticatedRecruiterReportsIndexRoute
  AuthenticatedRecruiterSchedulingIndexRoute: typeof AuthenticatedRecruiterSchedulingIndexRoute
}

const AuthenticatedRecruiterRouteRouteChildren: AuthenticatedRecruiterRouteRouteChildren =
  {
    AuthenticatedRecruiterIndexRoute: AuthenticatedRecruiterIndexRoute,
    AuthenticatedRecruiterCandidatesIdRoute:
      AuthenticatedRecruiterCandidatesIdRouteWithChildren,
    AuthenticatedRecruiterJobsNewRoute: AuthenticatedRecruiterJobsNewRoute,
    AuthenticatedRecruiterPersonasNewRoute:
      AuthenticatedRecruiterPersonasNewRoute,
    AuthenticatedRecruiterPersonasPromptRoute:
      AuthenticatedRecruiterPersonasPromptRoute,
    AuthenticatedRecruiterReportsInterviewIdRoute:
      AuthenticatedRecruiterReportsInterviewIdRoute,
    AuthenticatedRecruiterReportsComprehensiveRoute:
      AuthenticatedRecruiterReportsComprehensiveRoute,
    AuthenticatedRecruiterAnalyticsIndexRoute:
      AuthenticatedRecruiterAnalyticsIndexRoute,
    AuthenticatedRecruiterCandidatesIndexRoute:
      AuthenticatedRecruiterCandidatesIndexRoute,
    AuthenticatedRecruiterJobsIndexRoute: AuthenticatedRecruiterJobsIndexRoute,
    AuthenticatedRecruiterMonitorIndexRoute:
      AuthenticatedRecruiterMonitorIndexRoute,
    AuthenticatedRecruiterPersonasIndexRoute:
      AuthenticatedRecruiterPersonasIndexRoute,
    AuthenticatedRecruiterQuestionsIndexRoute:
      AuthenticatedRecruiterQuestionsIndexRoute,
    AuthenticatedRecruiterReportsIndexRoute:
      AuthenticatedRecruiterReportsIndexRoute,
    AuthenticatedRecruiterSchedulingIndexRoute:
      AuthenticatedRecruiterSchedulingIndexRoute,
  }

const AuthenticatedRecruiterRouteRouteWithChildren =
  AuthenticatedRecruiterRouteRoute._addFileChildren(
    AuthenticatedRecruiterRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCandidateRouteRoute: typeof AuthenticatedCandidateRouteRouteWithChildren
  AuthenticatedRecruiterRouteRoute: typeof AuthenticatedRecruiterRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCandidateRouteRoute:
    AuthenticatedCandidateRouteRouteWithChildren,
  AuthenticatedRecruiterRouteRoute:
    AuthenticatedRecruiterRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicCronInterviewRemindersRoute: ApiPublicCronInterviewRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
